const icons = [
  "adjust",
  "alert",
  "angle",
  "arrow-left-right",
  "up-down",
  "auto-layout-horizontal",
  "auto-layout-vertical",
  "back",
  "blend-empty",
  "blend",
  "break",
  "caret-down",
  "caret-left",
  "caret-right",
  "caret-up",
  "check",
  "close",
  "component",
  "corner-radius",
  "corners",
  "distribute-horizontal-spacing",
  "distribute-vertical-spacing",
  "draft",
  "effects",
  "ellipses",
  "eyedropper",
  "forward",
  "frame",
  "group",
  "hidden",
  "horizontal-padding",
  "hyperlink",
  "image",
  "instance",
  "key",
  "layout-align-bottom",
  "align-horizontal-centers",
  "align-left",
  "align-right",
  "align-top",
  "align-vertical-centers",
  "layout-grid-columns",
  "layout-grid-rows",
  "layout-grid-uniform",
  "library",
  "link-broken",
  "link-connected",
  "list-detailed",
  "list-tile",
  "list",
  "lock-off",
  "lock-on",
  "minus",
  "play",
  "plus",
  "random",
  "recent",
  "resize-to-fit",
  "resolve-filled",
  "resolve",
  "reverse",
  "search-large",
  "search",
  "settings",
  "share",
  "smiley",
  "sort-alpha-asc",
  "sort-alpha-dsc",
  "sort-top-bottom",
  "spacing",
  "spinner",
  "star-off",
  "star-on",
  "stroke-weight",
  "styles",
  "swap",
  "theme",
  "tidy-up-grid",
  "tidy-up-list-horizontal",
  "tidy-up-list-vertical",
  "timer",
  "trash",
  "vertical-padding",
  "visible",
  "warning-large",
  "warning",
];
const iconColors = [
  "blue",
  "purple",
  "purple4",
  "hot-pink",
  "green",
  "red",
  "yellow",
  "black",
  "black8",
  "black3",
  "white",
  "white8",
  "white4",
];
const sizes = ["small", "large", "xlarge"];
const weights = ["medium", "bold"];
const levels = ["h1", "h2", "h3", "h4", "h5", "h6"];
const checkboxTypes = ["checkbox", "switch", "radio"];

export const api = {
  button: [
    {
      name: "children",
      type: "string",
      defaultValue: "Button",
      isRequired: true,
    },
    {
      name: "className",
      type: "string",
      defaultValue: "",
    },
    {
      name: "isSecondary",
      type: "boolean",
      defaultValue: false,
    },
    {
      name: "isTertiary",
      type: "boolean",
      defaultValue: false,
    },
    {
      name: "isDisabled",
      type: "boolean",
      defaultValue: false,
    },
    {
      name: "isDestructive",
      type: "boolean",
      defaultValue: false,
    },
    {
      name: "onClick",
      type: "function",
      defaultValue: console.log,
    },
  ],
  checkbox: [
    {
      name: "label",
      type: "string",
      defaultValue: "Toggle me",
      isRequired: true,
    },
    {
      name: "className",
      type: "string",
      defaultValue: "",
    },
    {
      name: "type",
      type: "CheckboxTypes",
      options: checkboxTypes,
      defaultValue: "checkbox",
    },
    {
      name: "isDisabled",
      type: "boolean",
      defaultValue: false,
    },
    {
      name: "defaultValue",
      type: "boolean",
      isDisabled: true,
      defaultValue: false,
    },
    {
      name: "onChange",
      type: "function",
      defaultValue: console.log,
    },
  ],
  disclosure: [
    {
      name: "children",
      type: "string",
      defaultValue: "Disclosure content",
      isRequired: true,
    },
    {
      name: "label",
      type: "string",
      defaultValue: "Disclosure",
      isRequired: true,
    },
    {
      name: "className",
      type: "string",
      defaultValue: "",
    },
    {
      name: "isSection",
      type: "boolean",
      defaultValue: false,
    },
    {
      name: "isDefaultExpanded",
      type: "boolean",
      isDisabled: true,
      defaultValue: false,
    },
    {
      name: "onExpand",
      type: "function",
      defaultValue: console.log,
    },
  ],
  input: [
    {
      name: "placeholder",
      type: "string",
      defaultValue: "Placeholder",
      isRequired: true,
    },
    {
      name: "className",
      type: "string",
      defaultValue: "",
    },
    {
      name: "defaultValue",
      type: "string",
      defaultValue: "",
    },
    {
      name: "isDisabled",
      type: "boolean",
      defaultValue: false,
    },
    {
      name: "icon",
      type: "Icons",
      options: icons,
      defaultValue: "",
    },
    {
      name: "iconColor",
      type: "IconColors",
      options: iconColors,
      defaultValue: "",
    },
    {
      name: "onChange",
      type: "function",
      defaultValue: console.log,
    },
  ],
  textarea: [
    {
      name: "placeholder",
      type: "string",
      defaultValue: "Placeholder text...",
      isRequired: true,
    },
    {
      name: "rows",
      type: "number",
      defaultValue: 2,
      isRequired: true,
    },
    {
      name: "className",
      type: "string",
      defaultValue: "",
    },
    {
      name: "defaultValue",
      type: "string",
      defaultValue: "",
    },
    {
      name: "isDisabled",
      type: "boolean",
      defaultValue: false,
    },
    {
      name: "onChange",
      type: "function",
      defaultValue: console.log,
    },
  ],
  select: [
    {
      name: "placeholder",
      type: "string",
      defaultValue: "Placeholder text...",
      isRequired: true,
    },
    {
      name: "options",
      type: "SelectOption[]",
      defaultValue: [
        { value: 1, label: "Item 1" },
        { value: 2, label: "Item 2" },
      ],
      isRequired: true,
    },
    {
      name: "className",
      type: "string",
      defaultValue: "",
    },
    {
      name: "defaultValue",
      type: "string",
      isDisabled: true,
      defaultValue: "",
    },
    {
      name: "isDisabled",
      type: "boolean",
      defaultValue: false,
    },
    {
      name: "onExpand",
      type: "function",
      defaultValue: console.log,
    },
    {
      name: "onChange",
      type: "function",
      defaultValue: console.log,
    },
  ],
  divider: [
    {
      name: "className",
      type: "string",
      defaultValue: "",
    },
  ],
  title: [
    {
      name: "children",
      type: "string",
      defaultValue: "Title",
      isRequired: true,
    },
    {
      name: "className",
      type: "string",
      defaultValue: "",
    },
    {
      name: "size",
      type: "Sizes",
      options: sizes,
      defaultValue: "xlarge",
    },
    {
      name: "level",
      type: "Levels",
      options: levels,
      defaultValue: "",
    },
    {
      name: "weight",
      type: "Weights",
      options: weights,
      defaultValue: "bold",
    },
  ],
  label: [
    {
      name: "children",
      type: "string",
      defaultValue: "Label",
      isRequired: true,
    },
    {
      name: "className",
      type: "string",
      defaultValue: "",
    },
    {
      name: "size",
      type: "Sizes",
      options: sizes,
      defaultValue: "",
    },
    {
      name: "weight",
      type: "Weights",
      options: weights,
      defaultValue: "",
    },
  ],
  text: [
    {
      name: "children",
      type: "string",
      defaultValue: "Text",
      isRequired: true,
    },
    {
      name: "className",
      type: "string",
      defaultValue: "",
    },
    {
      name: "size",
      type: "Sizes",
      options: sizes,
      defaultValue: "",
    },
    {
      name: "weight",
      type: "Weights",
      options: weights,
      defaultValue: "",
    },
  ],
  tip: [
    {
      name: "children",
      type: "string",
      defaultValue: "Text tip",
      isRequired: true,
    },
    {
      name: "className",
      type: "string",
      defaultValue: "",
    },
    {
      name: "iconText",
      type: "string",
      defaultValue: "",
    },
    {
      name: "iconName",
      type: "Icons",
      options: icons,
      defaultValue: "",
    },
    {
      name: "iconColor",
      type: "IconColors",
      options: iconColors,
      defaultValue: "",
    },
  ],
  icon: [
    {
      name: "name",
      type: "Icons",
      options: icons,
      defaultValue: "alert",
      isRequired: true,
    },
    {
      name: "className",
      type: "string",
      defaultValue: "",
    },
    {
      name: "color",
      type: "IconColors",
      options: iconColors,
      defaultValue: "",
    },
    {
      name: "isSelected",
      type: "boolean",
      defaultValue: false,
    },
    {
      name: "isDisabled",
      type: "boolean",
      defaultValue: false,
    },
    {
      name: "string",
      type: "string",
      defaultValue: "",
    },
    {
      name: "onClick",
      type: "function",
      options: [
        {
          label: "without onClick",
          value: null,
        },
        {
          label: "with onClick (Icon become a Button)",
          value: console.log,
        },
      ],
      defaultValue: null,
    },
  ],
};
